title: "Crescent's Pages"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"

collections:
  pages:
    output: true
    permalink: /:collection/:path
