remote_theme: pages-themes/hacker@v0.2.0

title: "Crescent's Pages"

show_downloads: false
google_analytics: 

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      output: true
      layout: default

collections:
  pages:
    output: true
    label: "Pages"
    order: 1
  diablo_iv:
    output: true
    label: "Diablo IV"
    order: 2
