remote_theme: pages-themes/hacker@v0.2.0

title: "Crescent's Pages"

show_downloads: false
google_analytics: 

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      output: true
      layout: default

collections:
  pages:
    order: 1
    output: true
  diablo_iv:
    order: 2
    output: true
  Maybe:
    order: 3
    output: true
