theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: Crescent's Pages
author:
  name: Crescent
  email: aa0051320@gmail.com
description: >
The content of this project itself is licensed under the [Creative Commons Attribution 4.0 license](https://creativecommons.org/licenses/by/4.0/), 
and the underlying source code used to format and display that content is licensed under the [MIT license](LICENSE.md).
