remote_theme: pages-themes/hacker@v0.2.0

title: "Crescent's Pages"

show_downloads: false
google_analytics: 

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      output: true
      layout: default

collections:
  Pages:
    output: true
    permalink: /:title/
    order: 1
  Diablo_IV:
    output: true
    permalink: /:title/
    order: 2
