title: Crescent's Pages
description: Hacker is a theme for GitHub Pages.
show_downloads: false
google_analytics:

remote_theme: pages-themes/hacker@v0.2.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
