title: Crescent's Pages
# description: [A short description of your site's purpose]
author:
  name: Crescent Chen
  email: aa0051320@gmail.com

# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
