title: "Crescent's Pages"

# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       output: true

theme: minima

collections:
  pages:
    output: true
    permalink: /:collection/:title
