remote_theme: pages-themes/hacker@v0.2.0

title: "Crescent's Pages"

show_downloads: false
google_analytics: 

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      output: true

collections:
  Diablo_IV:
    order: 1
    output: true
    permalink: /:title/
